### ISSUE TITLE
Azure Pipelines fail while MSBuild@1 The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer

### ISSUE THREAD

**Issue by panos23kar** [microsoft/DacFx#459]
I used *Azure Data Studio* to build a *sql project* into an .**sqlproj** file which looks like that:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.12-preview" />
  <PropertyGroup>
    <Name>SOmeName</Name>
    <ProjectGuid>{xxxx-xxxxx}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="TestSchema" />
  </ItemGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
</Project>
```

I use **Azure Pipelines** (windows agent) to build the .**sqlproj** file using the **MSBuild@1** task:

```
          - task: MSBuild@1
            displayName: 'Build Project: *.sqlproj'
            inputs:
              solution: '**\*.sqlproj'
              platform: 'Any CPU'
              configuration: Release
```

Pipeline logs this error messsage:

```
error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found.
To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework
version or retarget yourapplication. You can download .NET Framework Developer Packs
at https://aka.ms/msbuild/developerpacks [C:\a\10\s\blabla]
```

**Comment by ErikEJ** [comment]
@panos23kar Use dotnet build

https://github.com/microsoft/DacFx

**Comment by panos23kar** [comment]
I did it (DotNet@2) without specifying version and still failed

**Comment by ErikEJ** [comment]
With which error??

**Comment by panos23kar** [comment]
@ErikEJ Same error 

```
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'

          - task: MSBuild@1
            displayName: 'Build Project: *.sqlproj'
            inputs:
              solution: '**\*.sqlproj'
              platform: 'Any CPU'
              configuration: Release
```

Still gives:

```
error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

**Comment by ErikEJ** [comment]
@panos23kar use the https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines task, not msbuild task.

Sorry if I was unclear...

**Comment by panos23kar** [comment]
@ErikEJ `DotNetCoreCLI@2 ` did the trick of building the sql project. Thanks a lot!!

**Comment by panos23kar** [comment]
DotNetCoreCLI@2 did the trick (https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines)

**Comment by humbberto** [comment]
I'am using `DotNetCoreCLI@2` and facing the same issue ;(
 
here is my pipeline 

```
name: $(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)
trigger:
- master

pr:
- master

pool:
  name: 'My-Pool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  netcoreVersion: 3.x

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk'
  inputs:
    packageType: sdk
    version: $(netcoreVersion)

- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
```

and this is the issue:
```
##[error]C:\agent\_work\_tool\dotnet\sdk\3.1.426\Microsoft.Common.CurrentVersion.targets(1177,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```
