### ISSUE TITLE
Add Pre-compare Script Option for DACPAC Publishing

### ISSUE THREAD

**Issue by dzsquared** [microsoft/DacFx#482]
https://developercommunity.visualstudio.com/t/Add-Pre-compare-Script-Option-for-DACPAC/10594162

Bringing this item over from VS Developer Community since the core implementation would be in Microsoft.Build.Sql and DacFx.

> Often times there are updates and revisions that need to be made to a database that cannot be automatically handled by a deployment script generated by a DACPAC, such as adding new non-nullable columns to a table or data migrations that must happen because a column or table is being dropped.

> The first instinct is to add a pre-deployment script with the code necessary to execute changes so that the DACPAC will publish correctly, but this fails because the pre-deployment script is run AFTER the comparison takes place to generate the deployment script. This has been a known source of confusion for at least 15 years (https://learn.microsoft.com/en-us/archive/blogs/gertd/pre-deployment-scripts) and there are still questions about it appearing on places like Stack Overflow and even issues being reported in the community feedback (https://developercommunity.visualstudio.com/t/SQL-database-project-pre-deployment-scri/224190?ref=native&refTime=1708466421969&refUserId=fd449ac5-d5e8-690b-8ba8-adeb29ac3e19).

> All of the workarounds require manually writing a change script to run before a DACPAC is published, which is fine, but then involve a variety of approaches to manage running the script outside of Visual Studio or the normal publishing process, or splitting known changes into separate source code updates that are checked in and published in stages, and so on. While these are all solutions that technically work, they are arguably confusing and convoluted.

> Would it be possible to add an additional feature to run a “pre-compare” script during publishing? This way users could include code for any changes they want to take place before a DACPAC performs a comparison. This would also enable developers to include this script as part of a .sqlproj, and have it automatically be handled as part of the normal publish process.

> The expected workflow would be:

> Run pre-compare script
> Compare and generate deployment script
> Run pre-deployment script
> Run deployment script
> Run post-deployment script

**Comment by tony-donley** [comment]
Thanks Drew! :-)

> The expected workflow would be:
> 
> Run pre-compare script
> Compare and generate deployment script
> Run pre-deployment script
> Run deployment script
> Run post-deployment script

It would also be nice to flag that 'pre-compare' script as '`One Time'` or '`Every Time`'.

'`One Time`' would be used for most advanced schema changes and data transformation, where the script should only execute once per target database and then be archived, not execute at every deployment.  Would that require something like a "schema version" mark in the target database to know if that script has executed or not?  Or would we just have to write our scripts to be stateless by reading the schema metadata and react conditionally?

'`Every Time` might do things like:
- set a maintenance flag earlier than the pre-deploy
- make temporary permission changes that are later reverted in the generated script or in post-deploy

**Comment by biltongza** [comment]
Chiming in here with my two cents, I love DACPACs for the mental model of "this is what my database should look like, make it happen" but this is an area where the experience could be better. As mentioned, sometimes there are things that I simply don't want the DACPAC to do, either because it can't (the non nullable column is an example) but also sometimes because the approach it takes to a change is not ideal and I want more control over it.

The other part of the experience that is not ideal, is that there is sometimes data that I want source controlled. For example static/seed data.

For this reason, I've landed up using something like DbUp twice: once as a pre-deployment step before the DACPAC, and once as a post-deployment step after the DACPAC. I use the pre-deployment for any changes like adding non nullable columns or anything else I don't want the DACPAC to change, and then the post-deployment for things like data.

I pick DbUp because it makes the experience much smoother, I don't need to focus as much on writing my scripts in an idempotent way because it uses a journaling table to know what has and hasn't been run yet.

It would be lovely if the DACPAC could handle this kind of scenario.

**Comment by ErikEJ** [comment]
Constantly seeing the need fir this, a simple option to simply execute a script would be so great

**Comment by dzsquared** [comment]
Apologies for the confusion @ErikEJ  - that roadmap item is calling out that for the script to get bundled into the dacpac for execution during deployment, Microsoft.Build.Sql would have to incorporate a new item. I would have better phrased it as "Pre-plan script support in DacFx previews (including Microsoft.Build.Sql and SqlPackage)"

The concept is still that it would impact deployment in this manner:

<img width="1564" height="874" alt="Image" src="https://github.com/user-attachments/assets/835d401a-0b68-4bc0-a6cb-a310bbfe693d" />

**Comment by dzsquared** [comment]
# Request for comments

We are working on adding a **pre-plan script** to SQL projects: a third script type, alongside [pre-deployment and post-deployment](https://learn.microsoft.com/en-us/sql/tools/sql-database-projects/concepts/pre-post-deployment-scripts?pivots=sq1-command-line) scripts, that runs before DacFx reverse-engineers the target database and compares it with the source model. The script would be included in the dacpac and could prepare the target for comparison, enabling scenarios such as data migrations required before making a column non-nullable or  before DacFx creates the deployment plan. Similar to pre/post-deployment scripts, a project can contain only one pre-plan script, with `:r` SQLCMD syntax available to compose it from multiple files.

```xml
<ItemGroup>
  <PrePlan Include="pre-plan.sql" />
</ItemGroup>
```

Before we finalize the design, we want to get feedback on the proposed behavior and limitations of pre-plan scripts. Any feedback on the proposed behavior, limitations, and scenarios is welcome. Please comment on this issue and we'll continue to provide updates as we release previews of the Microsoft.Build.Sql SDK and SqlPackage CLI that include pre-plan script support.

**Limitations of pre-plan scripts**:
- The T-SQL syntax in a pre-plan script must be able to be run inside a transaction. Operations like fulltext catalog/index operations, resumable index operations, and backup/restore are not supported. Build-time checks will make best effort to flag unsupported operations.
- Similar to pre/post-deployment scripts, pre-plan scripts should be authored with idempotent guardrails to avoid errors if the script is run multiple times. Upcoming functionality will surface dacpac versioning in a way that makes it easier to ensure portions of a script are only run once throughout a database's lifecycle.

For **Publish** actions, the proposal is to run the pre-plan script in a transaction before model comparison. If the script or deployment plan generation fails, the pre-plan script transaction would be rolled back; successfully beginning the deployment would commit the pre-plan script. Even if the publish property `IncludeTransactionalScripts` has been set to true, the pre-plan script would still be handled as a separate transaction that is committed once the deployment plan is successfully generated.

For **Script** actions, the proposal is to require the explicit choice of one of two modes for how the pre-plan script is handled. The script action is expected to be *read-only*, so the presence of a pre-plan script requires a decision to ensure that the executor is aware of the tradeoffs. The two modes are:
- /p:PrePlanScript=RunAndRollback — The pre-plan script is executed in a transaction against the target, the deployment plan is generated against the modified state, and then the transaction is rolled back. The pre-plan script is included in the script output returned to the user.
- /p:PrePlanScript=RunOnce — The pre-plan script is executed when generating the deployment plan, and if the plan generates successfully the pre-plan script transaction is committed. The pre-plan script is not included in the script output, since it has already been applied to the target.

 **Is requiring an explicit choice the right default for `Script` actions?** We especially want feedback on whether temporary execution under `RunAndRollback` meets your read-only expectations, whether you need a mode that never touches the target even if its plan may be inaccurate, and whether you would use `RunOnce` despite Script then making a persistent change.
- Does requiring the property selection for `/p:PrePlanScript` between "RunOnce" and "RunAndRollback" and having no default option make using pre-plan scripts with the Script action for deployments seem safer, less like running with scissors?
- Is the "RunOnce" property option a mode that you might use in the environments you deploy to?

**Comment by ErikEJ** [comment]
@dzsquared Awesome! 

"Is requiring an explicit choice the right default for Script actions?" 

not sure what you mean by this... so /a:script will not run if the .dacpac contains a preplan script unless you set one of the two options?

In that case RunAndRollback sounds like a good approach.

**Comment by dzsquared** [comment]
@ErikEJ - you're correct, the proposal is that /a:script will error/not run if there's a pre-plan script in the dacpac and the property /p:preplanscript hasn't been set. The intention is to keep anyone from being caught off guard by a script (even though they're rolled back). What we're very interested in is:
- does requiring option selection make pre-plan scripts and the /a:script action make them seem less like running with scissors (more safe)
- is the "runonce" option seem like something you might ever use, based on the environments you're deploying to

I'll edit the final question segment for clarity.

**Comment by ErikEJ** [comment]
@dzsquared I never actually use /a:script, but think that forcing users to set the option makes a lot of sense. On the other hand, if using scripts, I would never use RunOnce, as I assume this purpose of using scripts will then delay the actual publish process.

(My scripts usually contain destructive actions like column and table drops, and the occasional rename, all pretty breaking)

**Comment by CHerting-NI** [comment]
We implemented our own "pre-pre-deployment" script. But a solution from the tool would be very helpful.

**Comment by dzsquared** [comment]
@CHerting-NI - do you use your pre-pre-deployment scripts with the "script" action? do you have specific behavior expectations of it?

**Comment by CHerting-NI** [comment]
@dzsquared : Yes, with the script action. My expectation is that I have a script that runs automatically before database compare.

**Comment by ErikEJ** [comment]
@dzsquared an example of my current pipeline flow:

```yaml
                      - task: SqlAzureDacpacDeployment@1
                        displayName: Deploy DataLoss script using access token
                        inputs:
                          azureSubscription: ${{ parameters.serviceConnection }}
                          AuthenticationType: 'connectionString'
                          ConnectionString: 'Data Source=$(sqlServerFqdn);Initial Catalog=$(sqlDatabaseName);Encrypt=true;Connect Timeout=60'
                          deployType: 'SqlTask'
                          sqlFile: '$(Pipeline.Workspace)/drop/DataLossScript.sql'
                          SqlAdditionalArguments: '-AccessToken $(sqlAccessToken)'

                      - task: SqlAzureDacpacDeployment@1
                        displayName: Deploy .dacpac using access token
                        inputs:
                          azureSubscription: ${{ parameters.serviceConnection }}
                          AuthenticationType: 'connectionString'
                          ConnectionString: 'Data Source=$(sqlServerFqdn);Initial Catalog=$(sqlDatabaseName);Encrypt=true;Connect Timeout=60'
                          deployType: 'DacpacTask'
                          DeploymentAction: 'Publish'
                          DacpacFile: '$(Pipeline.Workspace)/drop/Database.Build.dacpac'
                          AdditionalArguments: '/AccessToken:$(sqlAccessToken)'
```
